namespace Merchant.BL_uTest
{
    public static class TestData
    {
        public static string orderJson =
 @"{
    'Content': [
    {
      'Id': 1,
      'ChannelName': 'Test channel',
      'ChannelId': 1,
      'GlobalChannelName': 'Custom Channel',
      'GlobalChannelId': 55,
      'ChannelOrderSupport': 'SPLIT_ORDER_LINES',
      'ChannelOrderNo': 'CE-TEST-60455',
      'MerchantOrderNo': 'GetInProgressData4',
      'Status': 'IN_PROGRESS',
      'IsBusinessOrder': false,
      'CreatedAt': '2020-06-15T11:17:05.99+02:00',
      'UpdatedAt': '2020-08-15T17:10:19.1166667+02:00',
      'MerchantComment': null,
      'BillingAddress': {
        'Line1': 'Teststreet 22',
        'Line2': null,
        'Line3': null,
        'Gender': 'NOT_APPLICABLE',
        'CompanyName': null,
        'FirstName': 'T.',
        'LastName': 'Tester',
        'StreetName': 'Teststreet',
        'HouseNr': '22',
        'HouseNrAddition': null,
        'ZipCode': '1111 TT',
        'City': 'Testtown',
        'Region': null,
        'CountryIso': 'NL',
        'Original': null
      },
      'ShippingAddress': {
        'Line1': 'Teststreet 22',
        'Line2': null,
        'Line3': null,
        'Gender': 'NOT_APPLICABLE',
        'CompanyName': null,
        'FirstName': 'T.',
        'LastName': 'Tester',
        'StreetName': 'Teststreet',
        'HouseNr': '22',
        'HouseNrAddition': null,
        'ZipCode': '1111 TT',
        'City': 'Testtown',
        'Region': null,
        'CountryIso': 'NL',
        'Original': null
      },
      'SubTotalInclVat': 7.5,
      'SubTotalVat': 1.3,
      'ShippingCostsVat': 0,
      'TotalInclVat': 7.5,
      'TotalVat': 1.3,
      'OriginalSubTotalInclVat': 7.5,
      'OriginalSubTotalVat': 1.3,
      'OriginalShippingCostsInclVat': 0,
      'OriginalShippingCostsVat': 0,
      'OriginalTotalInclVat': 7.5,
      'OriginalTotalVat': 1.3,
      'Lines': [
        {
          'Status': 'IN_PROGRESS',
          'IsFulfillmentByMarketplace': false,
          'Gtin': '8719351029609',
          'Description': 'T-shirt met lange mouw BASIC petrol: M',
          'StockLocation': null,
          'UnitVat': 1.3,
          'LineTotalInclVat': 7.5,
          'LineVat': 1.3,
          'OriginalUnitPriceInclVat': 7.5,
          'OriginalUnitVat': 1.3,
          'OriginalLineTotalInclVat': 7.5,
          'OriginalLineVat': 1.3,
          'OriginalFeeFixed': 0,
          'BundleProductMerchantProductNo': null,
          'JurisCode': null,
          'JurisName': null,
          'VatRate': 21,
          'ExtraData': [],
          'ChannelProductNo': '10717',
          'MerchantProductNo': '001201-M',
          'Quantity': 1,
          'CancellationRequestedQuantity': 0,
          'UnitPriceInclVat': 7.5,
          'FeeFixed': 0,
          'FeeRate': 0,
          'Condition': 'UNKNOWN',
          'ExpectedDeliveryDate': '2020-06-17T11:17:05.98+02:00'
        },{
          'Status': 'IN_PROGRESS',
          'IsFulfillmentByMarketplace': false,
          'Gtin': '8719351029609',
          'Description': 'T-shirt met lange mouw BASIC petrol: XS',
          'StockLocation': null,
          'UnitVat': 1.3,
          'LineTotalInclVat': 7.5,
          'LineVat': 1.3,
          'OriginalUnitPriceInclVat': 7.5,
          'OriginalUnitVat': 1.3,
          'OriginalLineTotalInclVat': 7.5,
          'OriginalLineVat': 1.3,
          'OriginalFeeFixed': 0,
          'BundleProductMerchantProductNo': null,
          'JurisCode': null,
          'JurisName': null,
          'VatRate': 21,
          'ExtraData': [],
          'ChannelProductNo': '10717',
          'MerchantProductNo': '001201-M',
          'Quantity': 5,
          'CancellationRequestedQuantity': 0,
          'UnitPriceInclVat': 7.5,
          'FeeFixed': 0,
          'FeeRate': 0,
          'Condition': 'UNKNOWN',
          'ExpectedDeliveryDate': '2020-06-17T11:17:05.98+02:00'
        }
      ],
      'Phone': '+31711000000',
      'Email': 'test@channelengine.net',
      'CompanyRegistrationNo': null,
      'VatNo': null,
      'PaymentMethod': 'iDEAL',
      'PaymentReferenceNo': null,
      'ShippingCostsInclVat': 0,
      'CurrencyCode': 'EUR',
      'OrderDate': '2020-06-15T11:17:05.99+02:00',
      'ChannelCustomerNo': null,
      'ExtraData': {
    'Extra Data': 'Custom Value'
      }
    },
    {
    'Id': 2,
      'ChannelName': 'Test channel',
      'ChannelId': 1,
      'GlobalChannelName': 'Custom Channel',
      'GlobalChannelId': 55,
      'ChannelOrderSupport': 'SPLIT_ORDER_LINES',
      'ChannelOrderNo': 'CE-TEST-83314',
      'MerchantOrderNo': 'GetInProgressData3',
      'Status': 'IN_PROGRESS',
      'IsBusinessOrder': false,
      'CreatedAt': '2020-06-15T11:16:58.48+02:00',
      'UpdatedAt': '2020-08-15T17:10:07.5633333+02:00',
      'MerchantComment': null,
      'BillingAddress': {
        'Line1': 'Teststreet 22',
        'Line2': null,
        'Line3': null,
        'Gender': 'NOT_APPLICABLE',
        'CompanyName': null,
        'FirstName': 'T.',
        'LastName': 'Tester',
        'StreetName': 'Teststreet',
        'HouseNr': '22',
        'HouseNrAddition': null,
        'ZipCode': '1111 TT',
        'City': 'Testtown',
        'Region': null,
        'CountryIso': 'NL',
        'Original': null
      },
      'ShippingAddress': {
        'Line1': 'Teststreet 22',
        'Line2': null,
        'Line3': null,
        'Gender': 'NOT_APPLICABLE',
        'CompanyName': null,
        'FirstName': 'T.',
        'LastName': 'Tester',
        'StreetName': 'Teststreet',
        'HouseNr': '22',
        'HouseNrAddition': null,
        'ZipCode': '1111 TT',
        'City': 'Testtown',
        'Region': null,
        'CountryIso': 'NL',
        'Original': null
      },
      'SubTotalInclVat': 9.5,
      'SubTotalVat': 1.65,
      'ShippingCostsVat': 0,
      'TotalInclVat': 9.5,
      'TotalVat': 1.65,
      'OriginalSubTotalInclVat': 9.5,
      'OriginalSubTotalVat': 1.65,
      'OriginalShippingCostsInclVat': 0,
      'OriginalShippingCostsVat': 0,
      'OriginalTotalInclVat': 9.5,
      'OriginalTotalVat': 1.65,
      'Lines': [
        {
        'Status': 'IN_PROGRESS',
          'IsFulfillmentByMarketplace': false,
          'Gtin': '8719351029609',
          'Description': 'T-shirt met lange mouw BASIC petrol: XL',
          'StockLocation': null,
          'UnitVat': 1.65,
          'LineTotalInclVat': 9.5,
          'LineVat': 1.65,
          'OriginalUnitPriceInclVat': 9.5,
          'OriginalUnitVat': 1.65,
          'OriginalLineTotalInclVat': 9.5,
          'OriginalLineVat': 1.65,
          'OriginalFeeFixed': 0,
          'BundleProductMerchantProductNo': null,
          'JurisCode': null,
          'JurisName': null,
          'VatRate': 21,
          'ExtraData': [],
          'ChannelProductNo': '10267',
          'MerchantProductNo': '001201-XL',
          'Quantity': 1,
          'CancellationRequestedQuantity': 0,
          'UnitPriceInclVat': 9.5,
          'FeeFixed': 0,
          'FeeRate': 0,
          'Condition': 'UNKNOWN',
          'ExpectedDeliveryDate': '2020-06-17T11:16:58.47+02:00'
        },{
        'Status': 'IN_PROGRESS',
          'IsFulfillmentByMarketplace': false,
          'Gtin': '8719351029609',
          'Description': 'T-shirt met lange mouw BASIC petrol: S',
          'StockLocation': null,
          'UnitVat': 1.3,
          'LineTotalInclVat': 15,
          'LineVat': 2.6,
          'OriginalUnitPriceInclVat': 7.5,
          'OriginalUnitVat': 1.3,
          'OriginalLineTotalInclVat': 15,
          'OriginalLineVat': 2.6,
          'OriginalFeeFixed': 0,
          'BundleProductMerchantProductNo': null,
          'JurisCode': null,
          'JurisName': null,
          'VatRate': 21,
          'ExtraData': [],
          'ChannelProductNo': '10924',
          'MerchantProductNo': '001201-S',
          'Quantity': 2,
          'CancellationRequestedQuantity': 0,
          'UnitPriceInclVat': 7.5,
          'FeeFixed': 0,
          'FeeRate': 0,
          'Condition': 'UNKNOWN',
          'ExpectedDeliveryDate': '2020-06-17T11:16:34.6933333+02:00'
        },
        {
        'Status': 'IN_PROGRESS',
          'IsFulfillmentByMarketplace': false,
          'Gtin': '8719351029609',
          'Description': 'T-shirt met lange mouw BASIC petrol: L',
          'StockLocation': null,
          'UnitVat': 1.48,
          'LineTotalInclVat': 8.5,
          'LineVat': 1.48,
          'OriginalUnitPriceInclVat': 8.5,
          'OriginalUnitVat': 1.48,
          'OriginalLineTotalInclVat': 8.5,
          'OriginalLineVat': 1.48,
          'OriginalFeeFixed': 0,
          'BundleProductMerchantProductNo': null,
          'JurisCode': null,
          'JurisName': null,
          'VatRate': 21,
          'ExtraData': [],
          'ChannelProductNo': '10374',
          'MerchantProductNo': '001201-L',
          'Quantity': 1,
          'CancellationRequestedQuantity': 0,
          'UnitPriceInclVat': 8.5,
          'FeeFixed': 0,
          'FeeRate': 0,
          'Condition': 'UNKNOWN',
          'ExpectedDeliveryDate': '2020-06-17T11:16:34.71+02:00'
        }
      ],
      'Phone': '+31711000000',
      'Email': 'test@channelengine.net',
      'CompanyRegistrationNo': null,
      'VatNo': null,
      'PaymentMethod': 'iDEAL',
      'PaymentReferenceNo': null,
      'ShippingCostsInclVat': 0,
      'CurrencyCode': 'EUR',
      'OrderDate': '2020-06-15T11:16:58.48+02:00',
      'ChannelCustomerNo': null,
      'ExtraData': {
        'Extra Data': 'Custom Value'
      }
},
    {
    'Id': 3,
      'ChannelName': 'Test channel',
      'ChannelId': 1,
      'GlobalChannelName': 'Custom Channel',
      'GlobalChannelId': 55,
      'ChannelOrderSupport': 'SPLIT_ORDER_LINES',
      'ChannelOrderNo': 'CE-TEST-18325',
      'MerchantOrderNo': 'GetInProgressData2',
      'Status': 'IN_PROGRESS',
      'IsBusinessOrder': false,
      'CreatedAt': '2020-06-15T11:16:50.4333333+02:00',
      'UpdatedAt': '2020-08-15T17:09:11.9533333+02:00',
      'MerchantComment': null,
      'BillingAddress': {
        'Line1': 'Teststreet 22',
        'Line2': null,
        'Line3': null,
        'Gender': 'NOT_APPLICABLE',
        'CompanyName': null,
        'FirstName': 'T.',
        'LastName': 'Tester',
        'StreetName': 'Teststreet',
        'HouseNr': '22',
        'HouseNrAddition': null,
        'ZipCode': '1111 TT',
        'City': 'Testtown',
        'Region': null,
        'CountryIso': 'NL',
        'Original': null
      },
      'ShippingAddress': {
        'Line1': 'Teststreet 22',
        'Line2': null,
        'Line3': null,
        'Gender': 'NOT_APPLICABLE',
        'CompanyName': null,
        'FirstName': 'T.',
        'LastName': 'Tester',
        'StreetName': 'Teststreet',
        'HouseNr': '22',
        'HouseNrAddition': null,
        'ZipCode': '1111 TT',
        'City': 'Testtown',
        'Region': null,
        'CountryIso': 'NL',
        'Original': null
      },
      'SubTotalInclVat': 7.5,
      'SubTotalVat': 1.3,
      'ShippingCostsVat': 0,
      'TotalInclVat': 7.5,
      'TotalVat': 1.3,
      'OriginalSubTotalInclVat': 7.5,
      'OriginalSubTotalVat': 1.3,
      'OriginalShippingCostsInclVat': 0,
      'OriginalShippingCostsVat': 0,
      'OriginalTotalInclVat': 7.5,
      'OriginalTotalVat': 1.3,
      'Lines': [
        {
        'Status': 'IN_PROGRESS',
          'IsFulfillmentByMarketplace': false,
          'Gtin': '8719351029609',
          'Description': 'T-shirt met lange mouw BASIC petrol: M',
          'StockLocation': null,
          'UnitVat': 1.3,
          'LineTotalInclVat': 7.5,
          'LineVat': 1.3,
          'OriginalUnitPriceInclVat': 7.5,
          'OriginalUnitVat': 1.3,
          'OriginalLineTotalInclVat': 7.5,
          'OriginalLineVat': 1.3,
          'OriginalFeeFixed': 0,
          'BundleProductMerchantProductNo': null,
          'JurisCode': null,
          'JurisName': null,
          'VatRate': 21,
          'ExtraData': [],
          'ChannelProductNo': '10134',
          'MerchantProductNo': '001201-S',
          'Quantity': 1,
          'CancellationRequestedQuantity': 0,
          'UnitPriceInclVat': 7.5,
          'FeeFixed': 0,
          'FeeRate': 0,
          'Condition': 'UNKNOWN',
          'ExpectedDeliveryDate': '2020-06-17T11:16:50.34+02:00'
        },{
        'Status': 'IN_PROGRESS',
          'IsFulfillmentByMarketplace': false,
          'Gtin': '8719351029609',
          'Description': 'T-shirt met lange mouw BASIC petrol: XXL',
          'StockLocation': null,
          'UnitVat': 1.3,
          'LineTotalInclVat': 15,
          'LineVat': 2.6,
          'OriginalUnitPriceInclVat': 7.5,
          'OriginalUnitVat': 1.3,
          'OriginalLineTotalInclVat': 15,
          'OriginalLineVat': 2.6,
          'OriginalFeeFixed': 0,
          'BundleProductMerchantProductNo': null,
          'JurisCode': null,
          'JurisName': null,
          'VatRate': 21,
          'ExtraData': [],
          'ChannelProductNo': '10924',
          'MerchantProductNo': '001201-S',
          'Quantity': 2,
          'CancellationRequestedQuantity': 0,
          'UnitPriceInclVat': 7.5,
          'FeeFixed': 0,
          'FeeRate': 0,
          'Condition': 'UNKNOWN',
          'ExpectedDeliveryDate': '2020-06-17T11:16:34.6933333+02:00'
        },
        {
        'Status': 'IN_PROGRESS',
          'IsFulfillmentByMarketplace': false,
          'Gtin': '8719351029609',
          'Description': 'T-shirt met lange mouw BASIC petrol: L',
          'StockLocation': null,
          'UnitVat': 1.48,
          'LineTotalInclVat': 8.5,
          'LineVat': 1.48,
          'OriginalUnitPriceInclVat': 8.5,
          'OriginalUnitVat': 1.48,
          'OriginalLineTotalInclVat': 8.5,
          'OriginalLineVat': 1.48,
          'OriginalFeeFixed': 0,
          'BundleProductMerchantProductNo': null,
          'JurisCode': null,
          'JurisName': null,
          'VatRate': 21,
          'ExtraData': [],
          'ChannelProductNo': '10374',
          'MerchantProductNo': '001201-L',
          'Quantity': 1,
          'CancellationRequestedQuantity': 0,
          'UnitPriceInclVat': 8.5,
          'FeeFixed': 0,
          'FeeRate': 0,
          'Condition': 'UNKNOWN',
          'ExpectedDeliveryDate': '2020-06-17T11:16:34.71+02:00'
        }
      ],
      'Phone': '+31711000000',
      'Email': 'test@channelengine.net',
      'CompanyRegistrationNo': null,
      'VatNo': null,
      'PaymentMethod': 'iDEAL',
      'PaymentReferenceNo': null,
      'ShippingCostsInclVat': 0,
      'CurrencyCode': 'EUR',
      'OrderDate': '2020-06-15T11:16:50.4333333+02:00',
      'ChannelCustomerNo': null,
      'ExtraData': {
        'Extra Data': 'Custom Value'
      }
}
  ],
  'Count': 3,
  'TotalCount': 3,
  'ItemsPerPage': 100,
  'StatusCode': 200,
  'LogId': null,
  'Success': true,
  'Message': null,
  'ValidationErrors': { }
}";
    }
}
